# Generated by Django 3.1.5 on 2021-03-14 16:28

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('file_extension', models.CharField(max_length=10, null=True)),
                ('attachment', models.FileField(null=True, upload_to=core.helpers.PathAndRename('medias'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
