# Generated by Django 4.0.4 on 2022-04-20 13:44

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('file_extension', models.CharField(max_length=10, null=True)),
                ('attachment', models.FileField(null=True, upload_to=core.helpers.PathAndRename('medias'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
    ]
