# Generated by Django 3.1.5 on 2021-03-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_auto_20210314_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('complaint_no', models.CharField(max_length=100, null=True)),
                ('complainant', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('CL', 'CLOSED')], default='OP', max_length=2)),
                ('complaint', models.TextField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
    ]
