# Generated by Django 4.0.4 on 2022-07-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-unit_no']},
        ),
    ]
