# Generated by Django 4.0.4 on 2022-07-29 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitactivity',
            old_name='moved_in_at',
            new_name='activity_at',
        ),
        migrations.RemoveField(
            model_name='unitactivity',
            name='moved_in_by',
        ),
        migrations.RemoveField(
            model_name='unitactivity',
            name='moved_out_at',
        ),
        migrations.RemoveField(
            model_name='unitactivity',
            name='moved_out_by',
        ),
        migrations.AddField(
            model_name='unitactivity',
            name='activity_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitactivity',
            name='activity_type',
            field=models.IntegerField(choices=[(1, 'Move in'), (2, 'Move out'), (3, 'Activate'), (4, 'Deactivate'), (5, 'Enable maintenance'), (6, 'Disabled maintenance')], default=1),
            preserve_default=False,
        ),
    ]
