# Generated by Django 3.1.5 on 2021-03-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietors', '0005_auto_20210315_0111'),
        ('units', '0002_auto_20210314_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='proprietor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proprietors.proprietor'),
        ),
        migrations.AddField(
            model_name='unit',
            name='proprietor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietors.proprietor'),
        ),
    ]
