# Generated by Django 4.0.4 on 2022-09-01 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_residentvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0003_rename_moved_in_at_unitactivity_activity_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lot_no', models.CharField(editable=False, max_length=100)),
                ('lot_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Motorcycle'), (3, 'Lorry')], default=1)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_lots', to='units.block')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_created', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_lots', to='units.floor')),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lot_no'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLotPass',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('access_card_no', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_modified', to=settings.AUTH_USER_MODEL)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_passes', to='units.parkinglot')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='residents.resident')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.residentvehicle')),
            ],
            options={
                'ordering': ['-started_at', 'parking_lot'],
            },
        ),
    ]
