# Generated by Django 4.0.4 on 2022-08-23 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0001_initial'),
        ('units', '0003_rename_moved_in_at_unitactivity_activity_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lot_no', models.CharField(editable=False, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_parking_lots', to='units.block')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_lots_created', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_parking_lots', to='units.floor')),
                ('last_modified_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_lots_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkings_owned', to='residents.resident')),
            ],
            options={
                'ordering': ['-lot_no'],
            },
        ),
    ]
