# Generated by Django 3.1.5 on 2021-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20210315_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='square_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_feet',
            field=models.IntegerField(default=0),
        ),
    ]
