# Generated by Django 3.1.5 on 2021-03-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietors', '0003_auto_20210314_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproprietor',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='historicalproprietor',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='proprietor',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='proprietor',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
