# Generated by Django 3.1.5 on 2021-03-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietors', '0004_auto_20210314_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproprietor',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='proprietor',
            name='unit',
        ),
    ]
