# Generated by Django 4.0.4 on 2022-04-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['-renter_no']},
        ),
        migrations.RenameField(
            model_name='renter',
            old_name='modified_at',
            new_name='last_modified_at',
        ),
    ]
