# Generated by Django 4.0.4 on 2022-07-27 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('resident_no', models.CharField(max_length=100, null=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('title', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.')], default=None, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('nric', models.CharField(max_length=255, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=None, null=True)),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_payment_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_last_modified', to=settings.AUTH_USER_MODEL)),
                ('resident_user', models.OneToOneField(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='user_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-resident_no'],
            },
        ),
    ]
