# Generated by Django 4.0.4 on 2022-08-24 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentVehicle',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('plate_no', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Motorcycle'), (3, 'Lorry')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_vehicles_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_vehicles_last_modified', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.resident')),
            ],
            options={
                'ordering': ['-plate_no'],
            },
        ),
    ]
