# Generated by Django 3.1.5 on 2021-03-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        ('units', '0002_auto_20210314_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bill_attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medias.media')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
    ]
