# Generated by Django 3.1.5 on 2021-03-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20210315_0111'),
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_billings', to='units.unit'),
        ),
    ]
